# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'oeciteamDockerHub'
    repository: 'sgx-test'
    command: 'buildAndPush'
    Dockerfile: 'k8s-sgxtest/Dockerfile'
    tags: |
      1.0
      latest